/*
 * Copyright 2021 msgmonster project
 *
 * Website: https://github.com/pinorobotics/msgmonster
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Message class for jrosclient
 *
 * Generated for ROS msg file: roborio_msgs/RoborioOdometry
 */

package org.frc.team4048.rosnetworktables;


import java.util.Objects;

import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.xfunction.XJson;
import id.xfunction.Preconditions;

/**
 * Definition for roborio_msgs/RoborioOdometry
 */
@MessageMetadata(
        name = RoborioOdometryMessage.NAME)
public class RoborioOdometryMessage implements Message {

    static final String NAME = "roborio_msgs/RoborioOdometry";

    public double x;

    public double y;

    public double yaw;

    public RoborioOdometryMessage withX(double x) {
        this.x = x;
        return this;
    }

    public RoborioOdometryMessage withY(double y) {
        this.y = y;
        return this;
    }

    public RoborioOdometryMessage withYaw(double yaw) {
        this.yaw = yaw;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                x,
                y,
                yaw
        );
    }

    @Override
    public boolean equals(Object obj) {
        var other = (RoborioOdometryMessage) obj;
        return
                x == other.x &&
                        y == other.y &&
                        yaw == other.yaw
                ;
    }

    @Override
    public String toString() {
        return XJson.asString(
                "x", x,
                "y", y,
                "yaw", yaw
        );
    }

}
